
import { IconEntry } from './types';

// Extracted from the provided code snippet's massive mapping
export const RAW_ICON_MAP: Record<string, string> = {
  'settings_1': '⚙️',
  'loop': '🔄',
  'error': '🛑',
  'security': '🔒',
  'performance': '⚡',
  'audit': '📜',
  'ai': '🧠',
  'cloud': '☁️',
  'data': '💾',
  'finance': '💰',
  'ecommerce': '🛒',
  'devops': '🛠️',
  'connect': '🔗',
  'alert': '🚨',
  'info': 'ℹ️',
  'check': '✅',
  'warning': '⚠️',
  'danger': '🚫',
  'upload': '📤',
  'download': '📥',
  'search': '🔍',
  'edit': '✏️',
  'delete': '🗑️',
  'add': '➕',
  'save': '💾',
  'reset': '↩️',
  'help': '❓',
  'analytics': '📊',
  'optimize': '✨',
  'validate': '✔️',
  'generate': '➕',
  'explain': '💬',
  'history': '🕰️',
  'learn': '📚',
  'predict': '🔮',
  'adapt': '🌱',
  'deploy': '🚀',
  'monitor': '👁️',
  'report': '📈',
  'config': '🔧',
  'user': '👤',
  'admin': '👑',
  'log': '📝',
  'server': '🖥️',
  'network': '🌐',
  'database': '🗄️',
  'storage': '📦',
  'api': '🔌',
  'message': '✉️',
  'event': '📢',
  'metric': '📉',
  'dashboard': '📺',
  'terminal': '👨‍💻',
  'branch': '🌿',
  'commit': '✅',
  'pull_request': '↔️',
  'merge': '🤝',
  'release': '🎁',
  'build': '🏗️',
  'test': '🧪',
  'package': '📦',
  'container': '🐳',
  'virtual_machine': '🖥️',
  'load_balancer': '⚖️',
  'firewall': '🧱',
  'vpn': '🔑',
  'encryption': '🔐',
  'key': '🔑',
  'certificate': '📜',
  'token': '🎫',
  'password': '🔑',
  'secret': '🤫',
  'policy': '📄',
  'rule': '📏',
  'workflow': '➡️',
  'pipeline': '➡️➡️➡️',
  'trigger': '⚡',
  'action': '🏃',
  'result': '🏆',
  'status': '🟢',
  'health': '❤️',
  'uptime': '⬆️',
  'latency': '⏱️',
  'throughput': '💨',
  'error_rate': '❌',
  'cpu': '🧠',
  'memory': '🧠',
  'disk': '💽',
  'network_io': '🌐',
  'process': '⚙️',
  'thread': '🧵',
  'queue': '〰️',
  'cache': '💨',
  'stream': '🌊',
  'batch': '🔢',
  'schedule': '🗓️',
  'task': '✅',
  'job': '💼',
  'worker': '👷',
  'node': '🌳',
  'cluster': '🌐',
  'region': '🌍',
  'zone': '📍',
  'data_center': '🏢',
  'environment': '🏞️',
  'production': '🚀',
  'staging': '🧪',
  'development': '🚧',
  'test_env': '🔬',
  'sandbox': '🏖️',
  'beta': '🌟',
  'alpha': '✨',
  'experimental': '🔬',
  'feature_flag': '🚩',
  'toggle': '🔛',
  'ab_test': '🔀',
  'canary': '🐦',
  'rollback': '↩️',
  'deploy_success': '✅',
  'deploy_fail': '❌',
  'release_notes': '📝',
  'documentation': '📚',
  'support': '📞',
  'community': '👥',
  'forum': '🗣️',
  'chat': '💬',
  'email': '📧',
  'phone': '☎️',
  'address': '🏠',
  'location': '📍',
  'currency': '💵',
  'price': '💲',
  'cost': '💸',
  'discount': '✂️',
  'tax': '🧾',
  'shipping': '📦',
  'payment': '💳',
  'invoice': '📄',
  'receipt': '🧾',
  'order': '🛒',
  'product': '📦',
  'service': '⚙️',
  'subscription': '📅',
  'plan': '📋',
  'tier': '🌟',
  'upgrade': '⬆️',
  'downgrade': '⬇️',
  'cancel': '🚫',
  'activate': '✅',
  'deactivate': '❌',
  'suspend': '⏸️',
  'resume': '▶️',
  'block': '🚫',
  'unblock': '🔓',
  'report_bug': '🐞',
  'feature_request': '💡',
  'feedback': '💬',
  'review': '⭐',
  'rating': '⭐',
  'like': '👍',
  'dislike': '👎',
  'share': '↗️',
  'export': '📤',
  'import': '📥',
  'print': '🖨️',
  'copy': '📄',
  'paste': '📋',
  'cut': '✂️',
  'undo': '↩️',
  'redo': '↪️',
  'find': '🔍',
  'replace': '🔁',
  'sort': '↕️',
  'filter': ' funnel',
  'group': '👥',
  'expand': '↔️',
  'collapse': '↕️',
  'maximize': ' maximise',
  'minimize': ' minimise',
  'close': '✖️',
  'open': '➡️',
  'full_screen': ' full screen',
  'exit_full_screen': ' exit full screen',
  'zoom_in': '🔍➕',
  'zoom_out': '🔍➖',
  'refresh': '🔄',
  'reload': '🔄',
  'back': '⬅️',
  'forward': '➡️',
  'home': '🏠',
  'menu': '☰',
  'dots_vertical': '⋮',
  'dots_horizontal': '⋯',
  'plus': '➕',
  'minus': '➖',
  'times': '✖️',
  'check_mark': '✅',
  'star': '⭐',
  'heart': '❤️',
  'bell': '🔔',
  'bell_slash': '🔕',
  'globe': '🌐',
  'map': '🗺️',
  'pin': '📍',
  'calendar': '📅',
  'clock': '⏰',
  'image': '🖼️',
  'video': '📹',
  'audio': '🎧',
  'file': '📄',
  'folder': '📁',
  'document': '📄',
  'book': '📖',
  'pencil': '✏️',
  'brush': '🖌️',
  'palette': '🎨',
  'camera': '📸',
  'mic': '🎤',
  'speaker': '🔊',
  'headset': '🎧',
  'gamepad': '🎮',
  'trophy': '🏆',
  'gift': '🎁',
  'present': '🎁',
  'award': '🏅',
  'medal': '🏅',
  'crown': '👑',
  'sparkles': '✨',
  'magic': '✨',
  'wand': '🪄',
  'lightbulb': '💡',
  'sun': '☀️',
  'moon': '🌙',
  'cloud_weather': '☁️',
  'rain': '🌧️',
  'snow': '🌨️',
  'thunderstorm': '⛈️',
  'wind': '🌬️',
  'temperature': '🌡️',
  'humidity': '💧',
  'globe_alt': ' Globe Alt',
  'chart_pie': ' Chart Pie',
  'chart_bar': ' Chart Bar',
  'chart_line': ' Chart Line',
  'trending_up': ' Trending Up',
  'trending_down': ' Trending Down',
  'finger_print': ' Finger Print',
  'shield_check': ' Shield Check',
  'shield_exclamation': ' Shield Exclamation',
  'bug': '🐞',
  'cube': '🧊',
  'puzzle': '🧩',
  'atom': '⚛️',
  'dna': '🧬',
  'robot': '🤖',
  'infinity': '♾️',
  'galaxy': '🌌',
  'star_of_life': '⚕️',
  'first_aid': '🩹',
  'hospital': '🏥',
  'ambulance': '🚑',
  'fire': '🔥',
  'water': '💧',
  'leaf': '🍃',
  'plant': '🌱',
  'tree': '🌳',
  'flower': '🌸',
  'animal': '🐾',
  'bird': '🐦',
  'fish': '🐠',
  'bug_insect': '🐛',
  'spider': '🕷️',
  'snake': '🐍',
  'dragon': '🐉',
  'phoenix': '🔥',
  'unicorn': '🦄',
  'mermaid': '🧜‍♀️',
  'alien': '👽',
  'ghost': '👻',
  'skull': '💀',
  'bomb': '💣',
  'gun': '🔫',
  'knife': '🔪',
  'sword': '⚔️',
  'axe': '🪓',
  'hammer': '🔨',
  'wrench': '🔧',
  'gear': '⚙️',
  'nut_bolt': '🔩',
  'magnet': '🧲',
  'light_switch': '💡',
  'plug': '🔌',
  'battery': '🔋',
  'bulb': '💡',
  'torch': '🔦',
  'candle': '🕯️',
  'bell_ring': '🔔',
  'alarm': '⏰',
  'siren': '🚨',
  'camera_movie': '📹',
  'tv': '📺',
  'radio': '📻',
  'cassette': '📼',
  'cd': '💿',
  'dvd': '📀',
  'record': ' रिकॉर्ड',
  'microphone': '🎤',
  'guitar': '🎸',
  'piano': '🎹',
  'drum': '🥁',
  'trumpet': '🎺',
  'violin': '🎻',
};

export const ICONS: IconEntry[] = Object.entries(RAW_ICON_MAP).map(([key, emoji]) => ({ key, emoji }));

export const ANALYZER_PROMPT = `
You are a React engineering expert. I am providing you with a custom JavaScript snippet that attempts to reimplement React core functionality from scratch.

Here is the code context:
- R module: A singleton managing internal cache 'c_' and a counter 'h_'.
- uS(iV): Simulated useState.
- uE(f, d): Simulated useEffect (basic execution).
- uM(f, d): Simulated useMemo.
- uR(iV): Simulated useRef.
- fC: Functional Component wrapper.
- I: A massive Icon component mapping strings to emojis.

The icon mapping is extremely repetitive, using 'alt', 'alt_alt', and 'alt_alt_alt' suffixes extensively for hundreds of entries.

Your goal is to answer questions about how this code works, its limitations compared to real React, and how one might improve it. Be concise, technical, and helpful.
`;
